### ISSUE TITLE
Format Exception in WslApi.GetDistributionList() where registry Lxss key contains a subkey without a GUID name

### ISSUE THREAD

**Issue by tip2tail** [Gitii/community.wsl.sdk#16]
Hello.

Thank you for this library which has proven very useful for a tool I have recently built.  I have spotted a minor issue where this fails with a "Format Exception" on certain user's machines.

It appears that a Microsoft process (I suspect a MS Store installation process) can leave a subkey in the `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss` hierarchy of the registry which has a non-GUID key name.  The key in question is called `AppxInstallerCache`.

![image](https://github.com/user-attachments/assets/c708cd5b-3534-41e1-82ee-137e8ff5fc75)

Having had a look at the code in the `GetDistributionList` routine, I can see that this makes an assumption that all subkeys are in the format of GUIDs.

**Comment by tip2tail** [comment]
Please see similar issues in other projects to confirm this is a "known" value in this registry key
* https://github.com/DDoSolitary/LxRunOffline/issues/171
* https://github.com/emeric-martineau/wsl-gui-tool/pull/6

**Comment by Gitii** [comment]
Hi, @tip2tail,
thanks for the bug report 👍

I have created an alpha release which contains a fix (non-guid sub keys will be skipped) and also added a .net 8 buid.
Please check if https://www.nuget.org/packages/Community.Wsl.Sdk/3.1.0-alpha1 is working for you.
The preview release will be identical to the official 3.1.0 release.

**Comment by tip2tail** [comment]
@Gitii 
Working great! Thank you!

**Comment by Gitii** [comment]
@tip2tail That are great new! I have created a new release 3.1.0
Thanks again for reporting the issue and feel free to suggest new features or reporting bugs in the future!
